### ISSUE TITLE
Ability to mock network failure?

### ISSUE THREAD

**Issue by sators** [ctimmerm/axios-mock-adapter#29]
Question: Is there a method to mock a network failure, say if the browser was offline trying to connect to an online resource?

**Comment by ctimmerm** [comment]
There's no built in way to do so currently. There are two ways a request can fail (other than the server returning an error code); by there being either a [low level network error](https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L83-L91) or if the request simply [timed out](https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L93-L99).

To emulate a network error, you can do the following for now:
```js
mock.onGet('/foo', function(config) {
  var error = new Error('Network Error');
  error.config = config;
  return Promise.reject(error);
});
```

I could add specific methods for these so you could do something like:
```js
mock.onGet('/foo').networkError();
mock.onPost('/bar').timeout();
```

**Comment by peterox** [comment]
I also think this would be great so I've just created a pull request to add it.

**Comment by cross311** [comment]
Can you also publish this update in the npm package?

**Comment by davidonlaptop** [comment]
yes, I would like to use this feature too!

**Comment by mpourismaiel** [comment]
Isn't this available in the npm package? I get typeError when trying to access `networkError` on `onPost`.

```TypeError: mockAxios.onPost(...).networkError is not a function```

And the solution @ctimmerm mentioned doesn't seem to work. I get 404 instead of a network error.

**Comment by linesh-simplicity** [comment]
@mpourismaiel the `networkError()` API is working on my end, so just a quick guess could this because of the package version? I'm working with `^1.9.0` version of `axios-mocks-adapter` and it's working for me. Can you post your library version so that we can have a look if it's the problem?
